### ISSUE TITLE
update monix to 3.3.0

### ISSUE THREAD

**Issue by ngbinh** [monix/monix-bio#198] opened 2020-11-12 04:32 UTC
I don't think `monix bio` 1.0.0 is binary compatible with `monix` 3.3.0 and it prevents us from upgrading monix. 

Thanks

**Comment by Avasil** [comment] 2020-11-12 09:06
Do you see any errors?

`monix-bio` depends on some internals that has changed so maybe that' the cause of the problem, I will try to prevent such situations in the future.

I plan to work on a new release in the weekend and release shortly after, we have already merged stack traces for IO[E, A] so it's not much left to do

**Comment by ngbinh** [comment] 2020-11-12 10:08
Yes, there is a missing symbol somewhere in monix stack traces. I saw that last week in our big code base CI at work. Will wait for the new release then.

**Comment by Avasil** [comment] 2020-11-15 19:13
I've released `1.1.0`, the issue should disappear: https://github.com/monix/monix-bio/releases/tag/v1.1.0

Sorry for the unpleasant surprise, I won't miss it again

**Closed by Avasil** 2020-11-15 19:13 UTC

**Comment by ngbinh** [comment] 2020-11-16 05:40
thanks a lot!
